### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by zhaoxvwahaha** [wdecoster/nanopack#10]
Does anybody know the installation error? Thanks in advance if you could give a hand.
pip install nanopack
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('timed out'))': /simple/nanopack/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('timed out'))': /simple/nanopack/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('timed out'))': /simple/nanopack/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('timed out'))': /simple/nanopack/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('timed out'))': /simple/nanopack/
ERROR: Could not find a version that satisfies the requirement nanopack (from versions: none)
ERROR: No matching distribution found for nanopack

**Comment by wdecoster** [comment]
That looks like general network problems on your side, or do you only see this with NanoPack?

**Comment by zhaoxvwahaha** [comment]
@wdecoster Thank you for prompt reply, I only see this with NanoPack, because I just insatlled another software. Any other install method I could use? Such as, download source code->make->install...

**Comment by zhaoxvwahaha** [comment]
@wdecoster Yes, you are right, my network is instability, I try it again and install successfully. Thank you very much, amazing software set.

**Comment by wdecoster** [comment]
Good to hear! Please let me know if you have any further questions or issues.
