### ISSUE TITLE
python3 setup.py error

### ISSUE THREAD

**Issue by lufuhao** [wdecoster/nanopack#12]
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    long_description=open(path.join(here, "README.rst")).read(),
  File "/usr/lib/python3.8/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/home/lufuhao/P5820T1D2T/Programs/nanopack/nanopack/README.rst'

**Comment by wdecoster** [comment]
Hi,

Well, it doesn't hurt to be polite or complete when opening an issue. 
Which command did you use to get this error? Why don't you install it through pip?

Regards,
Wouter

**Comment by lufuhao** [comment]
Sorry to disturb you. Very sorry if you feel any offense. Please delete this issue.

Thanks

**Comment by wdecoster** [comment]
Well there is no need for that either, I still want to help but just posting the error message without any context isn't very useful.

**Comment by lufuhao** [comment]
we would like to install any bio-program to a independent path in a special platform, such as HPC, and usually do that using python3 setup.py build and python3 setup.py —prefix. So every time when we need that program, try to source or load that or environment.

That error happens when running python3 setup.py build after git clone. It seems trying to read a description from a reader.rst file, which does not exist.

Thanks

Fuhao

发自我的iPhone

在 2020年11月2日，22:51，Wouter De Coster <notifications@github.com> 写道：

﻿

Reopened #12<https://github.com/wdecoster/nanopack/issues/12>.

**Comment by wdecoster** [comment]
I've made a change (https://github.com/wdecoster/nanopack/commit/e683f1e7a717fca7abc28d3bfac2debd777992f5) that should solve this, could you try to clone again?
