### ISSUE TITLE
PacBio

### ISSUE THREAD

**Issue by tiramisutes** [wdecoster/nanopack#2]
Isn't suitable for PacBio reads?

**Comment by wdecoster** [comment]
Oh yes, it's absolutely suitable for PacBio reads. If you have data in bam or (compressed)  fastq format it should just work without problems.

I will edit the description to clarify that.

**Comment by tiramisutes** [comment]
Yes, As I know, there are differences between PacBio and Illumina platform sequence output reads. there is encodes the quality values for the sequence in each line 4 for Illumina fastq format file, but not have for PacBio reads. Actually, no reads quality information for the PacBio sequence.

**Comment by wdecoster** [comment]
So you have your date in fasta format? I'm pretty sure I have seen PacBio data with quality scores?!
