### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by herrroaa** [wdecoster/nanopack#6]
Hi,
I tried to install nanopack, howeverI got this error (see below). I am using python 3.6.3.
Thanks
Tarek

----------------------------------------
Command "/Users/tarekmagdyshehatamohamed/miniconda3/envs/bioinfo/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/pm/y6_x4m551tx4l6b0kwnbh_ch0000gp/T/pip-install-zzj7rvj6/pysam/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/pm/y6_x4m551tx4l6b0kwnbh_ch0000gp/T/pip-record-36xsodxi/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/pm/y6_x4m551tx4l6b0kwnbh_ch0000gp/T/pip-install-zzj7rvj6/pysam/

**Comment by wdecoster** [comment]
Hi,

Is that the full output/error message?
Did you use pip for installation or conda?

Cheers,
Wouter

**Comment by Kwe-c** [comment]
After I installed pysam and mappy the installation of nanopack  was ok.
